# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Branch Name
      run: echo branch_name=$(echo $GITHUB_HEAD_REF) >> $GITHUB_ENV
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{env.branch_name}}
        fetch-depth: 0
    - name: Fail if modified files include any other files along with harness folder
      run: |
              nonconfig_modified_files_count=$(git diff --name-only origin/$GITHUB_BASE_REF -- . ':!harness' | wc -l)
              echo $nonconfig_modified_files_count
